### ISSUE TITLE
Conflict with multiple elements with the same name but different prefixes

### ISSUE THREAD

**Issue by mtorromeo** [media-io/yaserde#186]
Hi,
I'm trying to deserialize an XML which have multiple elements with the same name but defined in different namespaces and consequently using different prefixes.

The actual XSDs are rather complex, but the problem can be illustrated with this snippet:

```xml
<error>
  <reasonCode>1</reasonCode>
  <ext:reasonCode>1234</ext:reasonCode>
</error>
```

which I tried implementing with this struct:
```rs
pub struct ErrorType {
    #[yaserde(rename = "reasonCode", prefix = "myns")]
    pub reason_code: Option<u16>,
    #[yaserde(rename = "reasonCode", prefix = "ext")]
    pub ext_reason_code: Option<u16>,
}
```

but this results in the following error:
```
error[E0428]: the name `__Visitor_ReasonCode_` is defined multiple times
```

Is this supported?

**Comment by mtorromeo** [comment]
I got past this error with the following patch:
```patch
--- a/yaserde_derive/src/common/field.rs
+++ b/yaserde_derive/src/common/field.rs
@@ -90,6 +90,13 @@ impl YaSerdeField {
       },
     );
 
+    let prefix = self
+      .attributes
+      .prefix
+      .clone()
+      .map(|p| format!("{}_", p.to_upper_camel_case()))
+      .unwrap_or_default();
+
     let attribute = self
       .attributes
       .attribute
@@ -98,7 +105,8 @@ impl YaSerdeField {
 
     Ident::new(
       &format!(
-        "__Visitor_{attribute}{}_{}",
+        "__Visitor_{attribute}{}{}_{}",
+        prefix,
         label.replace('.', "_").to_upper_camel_case(),
         struct_id
       ),
```

But then I get a new error at runtime when trying to deserialize an element `<ext:reasonCode>`:
```
bad namespace for reasonCode, found http://example.com/ext
```

It seems like yaserde reads the "reasonCode" name and expects it to use the namespace of "myns" instead of considering the "ext" prefix?

**Comment by mtorromeo** [comment]
@MarcAntoine-Arnaud sorry to ping you, but is there any chance that you could take a look at this?

**Comment by MarcAntoine-Arnaud** [comment]
Hi @mtorromeo ,

Sorry for the delay.
Thank you for your analysis, it was the good way, just missing to complete the match with namespace.

I have implemented it in https://github.com/media-io/yaserde/commit/a067b85ee2ade328169f925d09b27882f2cd6117
and released in yaserde v0.11.

Please close the issue if it's complete once you've validated.

**Comment by mtorromeo** [comment]
Just wanted to let you know that I plan to get back to you with my feedback as soon as I can test it, but it'll probably take a week or two.

In the meantime, thank you for your work!

**Comment by mtorromeo** [comment]
Hi, I did some tests. The specific issue with homonymous elements is fixed, but I am having some other problems using mixed namespaces.

I think it's issue #177

**Comment by mtorromeo** [comment]
I think the same issue is still present for enum variants.

To use the same example used previously, this enum does not work properly:

```rs
    pub enum ErrorCodeType {
        #[yaserde(rename = "reasonCode", prefix = "myns")]
        ReasonCode(u16),

        #[yaserde(rename = "reasonCode", prefix = "ext")]
        StrReasonCode(String),

        #[default]
        #[allow(non_camel_case_types)]
        __undefined__,
    }
```
